apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-default-admin
  namespace: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-admin
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Name }}
  name: {{ .Release.Name }}-default-admin